# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '2 7 * * *'
    # 每天中国时间0点2分 (UTC时间前一天16点2分)
    - cron:  '2 16 * * *'
    # 每天UTC时间0点2分
    - cron:  '2 0 * * *'
  workflow_dispatch:    # ← 加上这一行，缩进要和 schedule 对齐
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v5.3.0
      with:
        distribution: 'temurin'          # 需要指定 JDK 发行版
        java-version: 26.0.1+8
    - name: current date
      run: date
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
     
    - name: Commit files
      run: |
         git config --local user.email "liuxiaolei5214@gmail.com"
         git config --local user.name "liuxiaolei5214"
         git pull
         git add README.md
         git add bing-wallpaper.md
         git add picture/*
         git add docs/*
         git add zh-cn/*
         git commit -m "update readme.md"
    - name: Debug token
      run: |
        if [ -n "${{ secrets.MY_GIT_TOKEN }}" ]; then
          echo "Token exists (length: ${#MY_GIT_TOKEN})"
        else
          echo "Token is EMPTY!"
        fi
      env:
        MY_GIT_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
    - name: Commit and Push changes
      env:
        TOKEN: ${{ secrets.MY_GIT_TOKEN }}
      run: |
        git config --local user.email "liuxiaolei5214@gmail.com"
        git config --local user.name "liuxiaolei5214"
        
        # 强制删除 GitHub Actions 默认的认证头（这个头会覆盖 Token）
        git config --local --unset http.https://github.com/.extraheader || true
    
        # 用 Token 重写远程地址
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/liuxiaolei5214/bing-wallpaper.git
    
        git add README.md bing-wallpaper.md picture/ docs/ zh-cn/
        git commit -m "auto update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
    
        # 推送
        git push origin main
